## ↗️ Домашнє завдання №1. До тем 1-3

**Студент:** Андрій Єрмольчев

**Група:** AI&ML 4

Вітаємо вас в першому домашньому завданні на цій дисципліні!

Це домашнє завдання є комплексним, бо охоплює такі теми:

- **Тема 1.** Лінійна алгебра. Вектори, матриці та операції
- **Тема 2.** Аналітична геометрія. Довжина, відстань та проєкції
- **Тема 3.** Системи рівнянь та застосування

Необхідно буде розв’язати різні **4 задачі**, кожна з яких оцінюється в **25 балів і** буде вимагати від вас аналітичних або/та програмних рішень.

Якщо з програмним — тут, мабуть, зрозуміло, що мається на увазі написання коду з Python, то що означає «аналітичне рішення»?

Це, грубо кажучи, звичайне «класичне рішення» — як ви розв’язували задачі в школі.

Таке комплексна домашня робота допоможе підсумувати вивчене та бути готовими розпочати роботу над подальшими темами.

Готові розпочати? До робити! 🏋🏻‍♂️

Imports:

In [ ]:
import numpy as np

# Задача 1. Робота з зображеннями як з матрицями

### Умова

Цифрові зображення у комп'ютері зберігаються як масиви чисел (матриці). Будь-яке чорно-біле зображення для комп'ютера — це просто матриця чисел, де кожне число — яскравість пікселя від 0 до 255. Редагування зображень базується на арифметичних операціях з цими матрицями.

Ви працюєте з фрагментом зображення розміром $3 \times 3$ пікселі.

Дано матрицю зображення $M$ та матрицю накладеного ефекту $E$:
$M = \begin{pmatrix} 100 & 150 & 200 \\ 50 & 100 & 150 \\ 0 & 50 & 100 \end{pmatrix}$ , $E = \begin{pmatrix} 20 & 30 & 40 \\ 10 & 20 & 30 \\ 5 & 10 & 15 \end{pmatrix}$

Необхідно реалізувати три алгоритми обробки:

- **Зміна контрасту.** Необхідно зменшити яскравість зображення $M$. Це множення матриці на скаляр (число) $\lambda$. Кожен елемент матриці множиться на це число 0.5
- **Корекція яскравості**. Це додавання скаляра $c$ до матриці $M$. Число додається до *кожного* елемента матриці. Додайте до зображення $M$ число 25. Це збільшить яскравість кожного пікселя на 25.
- **Змішування (Blending)**. Ми створюємо нове зображення, змішуючи оригінал та ефект у певній пропорції. Для цього створи нове зображення як лінійну комбінацію: $0.8 \cdot M + 0.2 \cdot E$. Це імітує прозорість ефекту.

Завдання:

1. Обчисліть це аналітично та покажіть проміжні кроки.
2. Використовуючи бібліотеку `numpy`, напишіть програму, що виконує ті самі операції та перевіряє твої аналітичні обчислення. Виведіть на екран результати обчислень для кожного фільтра.

### Критерії оцінювання (25 балів)

| **Критерій** | **Бали** | **Вимоги** |
| --- | --- | --- |
| Аналітичний розв’язок | 10 | Аналітичні обчислення виконані правильно |
| Код: Ініціалізація | 5 | Коректно створені масиви NumPy |
| Код: Операції | 5 | Реалізовано всі три операції |
| **Код та вивід** | 5 | Код запускається без помилок, результати виводяться та збігаються з аналітикою. |


## 1. Аналітичні обчислення

### Початкові матриці

Матриця зображення \( M \):



$
M =
\begin{pmatrix}
100 & 150 & 200 \\
50 & 100 & 150 \\
0 & 50 & 100
\end{pmatrix}
$



Матриця ефекту \( E \):



$
E =
\begin{pmatrix}
20 & 30 & 40 \\
10 & 20 & 30 \\
5 & 10 & 15
\end{pmatrix}
$



---

### 1.1. Зміна контрасту (множення на скаляр 0.5)

Множимо кожен елемент матриці \( M \) на 0.5:



$
0.5M =
\begin{pmatrix}
50 & 75 & 100 \\
25 & 50 & 75 \\
0 & 25 & 50
\end{pmatrix}
$



---

### 1.2. Корекція яскравості (додавання скаляра 25)

Додаємо 25 до кожного елемента матриці \( M \):



$
M + 25 =
\begin{pmatrix}
125 & 175 & 225 \\
75 & 125 & 175 \\
25 & 75 & 125
\end{pmatrix}
$



---

### 1.3. Змішування (Blending): \(0.8M + 0.2E\)

Обчислюємо поелементно:



$
0.8M + 0.2E =
\begin{pmatrix}
84 & 126 & 168 \\
42 & 84 & 126 \\
1 & 42 & 83
\end{pmatrix}
$

## 2. Реалізація в Python

In [1]:
import numpy as np

# Початкові матриці
M = np.array([
    [100, 150, 200],
    [50, 100, 150],
    [0, 50, 100]
])

E = np.array([
    [20, 30, 40],
    [10, 20, 30],
    [5, 10, 15]
])

# 1) Зміна контрасту
contrast = 0.5 * M

# 2) Корекція яскравості
brightness = M + 25

# 3) Змішування
blend = 0.8 * M + 0.2 * E

print("0.5 * M:\n", contrast)
print("\nM + 25:\n", brightness)
print("\n0.8 * M + 0.2 * E:\n", blend)


0.5 * M:
 [[ 50.  75. 100.]
 [ 25.  50.  75.]
 [  0.  25.  50.]]

M + 25:
 [[125 175 225]
 [ 75 125 175]
 [ 25  75 125]]

0.8 * M + 0.2 * E:
 [[ 84. 126. 168.]
 [ 42.  84. 126.]
 [  1.  42.  83.]]


---
---
---

# Задача 2. Пошук схожих фільмів

### Умова

Рекомендаційні системи як Netflix або YouTube часто представляють користувачів та контент у вигляді векторів.

Є профіль користувача — це вектор інтересів до жанрів `[Екшн, Комедія, Драма]`. Також є три фільми $A, B, C$, кожен з яких має таку ж структуру характеристик.

Вектор профілю користувача: $\mathbf{u} = (8, 2, 5)$

Та три фільмів.

- Фільм A (Action Movie): $\mathbf{v}_A = (9, 1, 2)$
- Фільм B (Comedy Movie): $\mathbf{v}_B = (1, 9, 8)$
- Фільм C (Drama Movie): $\mathbf{v}_C = (7, 2, 6)$

Ваша задача — знайти фільм, який найбільше підходить користувачу, порівнявши вектори їхніх характеристик.

📐Нагадуємо, чим менший кут між цими векторами у багатовимірному просторі, тим більше схожі об'єкти. Мірою цієї схожості є **косинусна подібність**. Вона показує, наскільки вектори "дивляться" в один бік. Значення коливається від -1 (протилежні) до 1 (ідентичні).

Формула косинусної подібності:
$\cos \theta = \cfrac{\mathbf{u} \cdot \mathbf{v}}{\|\mathbf{u}\| \cdot \|\mathbf{v}\|}$,

де $\mathbf{u} \cdot \mathbf{v}$ — скалярний добуток, а $\|\mathbf{u}\|, \|\mathbf{v}\|$ — довжина (норма) вектора.

**Аналітична частина розв'язку**.

1. Обчисліть аналітично норму вектора користувача $\|\mathbf{u}\|$
2. Обчисліть схожість (similarity score) профілю користувача з кожним із трьох фільмів.
3. Порівняйте отримані значення та визначте, який фільм має найвищий бал схожості.

**Програмна частина розв'язку.** Використовуючи бібліотеку `numpy` напишіть програму та виконайте наступні кроки:

1. Створіть вектор профілю користувача та вектори фільмів
2. Реалізуйте функцію косинусної схожості за формулою
3. Обчисліть схожість для кожного фільму
4. Виведіть на екран коефіцієнти схожості для кожного фільму та назву фільму, вектор якого має найбільше значення косинусної подібності.
5. Перевірте себе та порівняйте з аналітичними обчисленнями, щоб вони збігалися

### Критерії оцінювання (25 балів)

| **Критерій** | **Бали** | **Вимоги** |
| --- | --- | --- |
| Аналітичний розв’язок | 10 | Аналітичні обчислення виконані правильно |
| Код: Математика | 5 | Правильно реалізована формула косинусної подібності (скалярний добуток / добуток довжин). |
| Код: Обчислення | 5 | Отримані коефіцієнти для всіх трьох фільмів. |
| **Результат** | 5 | Програмно або логічно визначено та виведено найкращий фільм. |



Рішення:

## 1. Аналітична частина

### 1.1. Норма вектора користувача

Вектор користувача:

$u = (8, 2, 5)$

Обчислюємо норму:

$‖u‖ = \sqrt{8^2 + 2^2 + 5^2}$  
$‖u‖ = \sqrt{64 + 4 + 25}$  
$‖u‖ = \sqrt{93}$

---

### 1.2. Косинусна подібність з фільмами

Формула косинусної подібності:

$cos(u, v) = \frac{(u · v)}{‖u‖ · ‖v‖}$

---

#### Фільм A

$v_A = (9, 1, 2)$

$u · v_A = 8·9 + 2·1 + 5·2 = 84$  
$‖v_A‖ = \sqrt{9^2 + 1^2 + 2^2} = \sqrt{86}$

$cos(u, v_A) = \frac{84}{\sqrt{93} · \sqrt{86}}$

---

#### Фільм B

$v_B = (1, 9, 8)$

$u · v_B = 66$ 
$‖v_B‖ = \sqrt{146}$

$cos(u, v_B) = \frac{66}{\sqrt{93} · \sqrt{146}}$

---

#### Фільм C

$v_C = (7, 2, 6)$

$u · v_C = 90$  
$‖v_C‖ = \sqrt{89}$

$cos(u, v_C) = \frac{90}{\sqrt{93} · \sqrt{89}}$

---

### 1.3. Висновок

Найбільше значення косинусної подібності має фільм **C**, тому він найкраще відповідає профілю користувача.


## 2. Реалізація в Python

In [8]:
import numpy as np

# Вектори
u = np.array([8, 2, 5])
vA = np.array([9, 1, 2])
vB = np.array([1, 9, 8])
vC = np.array([7, 2, 6])

def cosine_similarity(a, b):
    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))

# Обчислення
sim_A = cosine_similarity(u, vA)
sim_B = cosine_similarity(u, vB)
sim_C = cosine_similarity(u, vC)

print("||u|| =", np.linalg.norm(u))
print("cos(u, A) =", sim_A)
print("cos(u, B) =", sim_B)
print("cos(u, C) =", sim_C)

# Вибір найкращого фільму
sims = {
    "Film A": sim_A,
    "Film B": sim_B,
    "Film C": sim_C
}

best_film = max(sims, key=sims.get)

print("\nBest match:", best_film, "with similarity =", sims[best_film])


||u|| = 9.643650760992955
cos(u, A) = 0.9392659661346112
cos(u, B) = 0.5664036369783693
cos(u, C) = 0.9892499382749278

Best match: Film C with similarity = 0.9892499382749278


---
---
---

# Задача 3. Аналіз виробництва

### **Умова**

Ви керуєте цехом зі збірки FPV-дронів. У вас є три моделі: "Розвідник" $x_1$, "Камікадзе" $x_2$ та важкий "Вантажний" дрон $x_3$. Кожен із них потребує різного набору комплектуючих: моторів, польотних контролерів та акумуляторів.

В кінці зміни приходить звіт про загальні витрати деталей, але через збій у системі ти втратив дані про те, скільки саме дронів кожного типу було зібрано. Це класична задача на відновлення даних, яка вирішується через систему лінійних рівнянь $A\mathbf{x} = \mathbf{b}$.

Відомі витрати на один дрон, це матриця $A$, де стовпці — це типи дронів:

- "Розвідник": 4 мотори, 1 контролер, 1 акумулятор.
- "Камікадзе": 4 мотори, 1 контролер, 2 акумулятори.
- "Вантажний": 6 моторів, 2 контролери, 4 акумулятори.

Всього за зміну було витрачено вектор $\mathbf{b}$:

- 460 моторів
- 130 контролерів
- 240 акумуляторів

Використовуючи бібліотеку `numpy`, напишіть програму та виконайте наступні кроки:

1. Сформуйте матрицю коефіцієнтів $A$ та вектор вільних членів $\mathbf{b}$.
2. Перед розв'язанням перевірте, чи має система єдиний розв'язок. Для цього обчисліть визначник матриці $A$ за допомогою функції `np.linalg.det(A)`. Якщо він не дорівнює нулю — розв'язок існує.
3. Розв'яжіть систему за допомогою `np.linalg.solve(A, b)` і знайдіть вектор $\mathbf{x}$. Це буде кількість зібраних дронів кожного типу.
4. Виконайте перевірку правильності розрахунків: перемножте матрицю $A$ на знайдений вектор $\mathbf{x}$. Результат має збагатися з вектором $\mathbf{b}$.
5. Виведіть кількість дронів кожного типу та результати перевірки.

### Критерії оцінювання (25 балів)

| **Критерій** | **Бали** | **Вимоги** |
| --- | --- | --- |
| **Ініціалізація** | 7 | Правильно сформована матриця $A$ та вектор $\mathbf{b}$. |
| **Аналіз** | 6 | Обчислено визначник, зроблено висновок. |
| **Розв'язок** | 7 | Знайдено коректний вектор $\mathbf{x}$. |
| **Перевірка** | 5 | Виконано перевірку $A\mathbf{x} = \mathbf{b}$. |


Рішення:

Є три моделі дронів:
- x1 — "Розвідник"
- x2 — "Камікадзе"
- x3 — "Вантажний"

Матриця витрат деталей на один дрон $A$:

Розвідник: 4 мотори, 1 контролер, 1 акумулятор  
Камікадзе: 4 мотори, 1 контролер, 2 акумулятори  
Вантажний: 6 моторів, 2 контролери, 4 акумулятори  

Матриця $A$ (рядки — типи деталей, стовпці — типи дронів):

$
\begin{pmatrix} 
  4 & 4 & 6 \\  
  1 & 1 & 2 \\  
  1 & 2 & 4  
\end{pmatrix}
$

Вектор витрат за зміну $b$:

$b = (460, 130, 240)$

Потрібно знайти $x = (x_1, x_2, x_3)$, де:
$A$ * x = $b$

---

#### Кроки розв'язання

1. Створити матрицю $A$ та вектор $b$.  
2. Перевірити, чи існує єдиний розв'язок: det($A$) ≠ 0.  
3. Розв'язати систему: `x = np.linalg.solve(A, b)`.  
4. Виконати перевірку: $A$ @ x має дорівнювати $b$.  
5. Вивести кількість дронів кожного типу.


In [7]:
import numpy as np

# 1. Матриця коефіцієнтів A
A = np.array([
    [4, 4, 6],   # мотори
    [1, 1, 2],   # контролери
    [1, 2, 4]    # акумулятори
])

# 2. Вектор витрат b
b = np.array([460, 130, 240])

# Перевірка визначника
detA = np.linalg.det(A)
print("Детермінант A:", detA)

if abs(detA) < 1e-9:
    print("Система не має єдиного розв'язку.")
else:
    # 3. Розв'язання системи
    x = np.linalg.solve(A, b)
    print("\nКількість зібраних дронів:")
    print("Розвідник (x1):", x[0])
    print("Камікадзе (x2):", x[1])
    print("Вантажний (x3):", x[2])

    # 4. Перевірка
    check = A @ x
    print("\nПеревірка A * x:")
    print(check)
    print("\nОчікуваний вектор b:")
    print(b)


Детермінант A: -2.0

Кількість зібраних дронів:
Розвідник (x1): 20.0
Камікадзе (x2): 50.0
Вантажний (x3): 30.0

Перевірка A * x:
[460. 130. 240.]

Очікуваний вектор b:
[460 130 240]


---
---
---

# Задача 4. Прогноз тренду

### Умова

При моніторингу IT-інфраструктури дані часто надходять із шумом.

Навантаження на CPU сервера може коливатися, але загальний тренд вказує на поступове зростання. Щоб передбачити, коли сервер досягне критичного навантаження, потрібно побудувати лінію тренду $y = kx + b$.

Оскільки точки не лежать ідеально на одній прямій, точного розв'язку системи не існує, тому використовується метод найменших квадратів (МНК).

Дано виміри завантаження CPU $y$ протягом 5 годин $t$:

- Час $t = [1, 2, 3, 4, 5]$
- Навантаження $y = [22,28,37,45,53]$

Використовуючи бібліотеку `numpy`, напишіть програму та виконайте наступні кроки:

1. Сформуйте матрицю $A$. Пам'ятайте, що для знаходження вільного члена $b$ матриця повинна містити стовпчик зі значень $t$ та стовпчик з одиниць.
2. Знайдіть коефіцієнти прямої $k$ та $b$ за допомогою функції `np.linalg.lstsq(A, y)`. Ця функція повертає найкращий наближений розв'язок.
3. Використовуючи знайдені коефіцієнти, обчисліть прогнозоване навантаження на **6-ту годину** за формулою $\hat{y} = k \cdot 6 + b$.
4. Виведіть рівняння отриманого тренду та прогноз.

**Опціональне завдання** з зірочкою (+5 бонусних балів). Функція `np.linalg.lstsq()` використовує нормальне рівняння для знаходження оптимальних коефіцієнтів. Реалізуйте цей метод вручну.

Знайдіть коефіцієнти $k$ - нахил, та $b$ - зсув через нормальне рівняння $A^T A \mathbf{x} = A^T \mathbf{y}$. Де $\mathbf{x} = [k, b]^T$ — вектор невідомих коефіцієнтів.

**Кроки:**

1. Обчислити $A^T A$
2. Обчислити $A^T \mathbf{y}$
3. Розв'яжіть систему через `np.linalg.solve()`
4. Порівняйте результат з `lstsq` — вони мають збігатися

### Критерії оцінювання (25 балів)

| **Критерій** | **Бали** | **Вимоги** |
| --- | --- | --- |
| **Підготовка даних** | 6 | Правильно сформована матриця $A$ (стовпчик $t$ + стовпчик одиниць). |
| **МНК** | 7 | Отримано коефіцієнти $k, b$ через `lstsq`. |
| **Прогноз** | 6 | Математично вірний розрахунок для 6-ї години. |
| **Вивід** | 6 | Виведено рівняння тренду та прогноз. |


Рішення:

Маємо дані вимірів:

- Час $t = (1, 2, 3, 4, 5)$
- Навантаження $y = (22, 28, 37, 45, 53)$

Потрібно знайти лінію тренду:

$y = k * t + b$

за методом найменших квадратів (МНК), а потім спрогнозувати навантаження на 6-ту годину.

---

### Кроки

1. Сформувати матрицю $A$:

   A має містити:
   - перший стовпчик — значення $t$
   - другий стовпчик — одиниці (для вільного члена $b$)

   Тобто:

$A =
\begin{pmatrix} 
     1 & 1 \\
     2 & 1 \\
     3 & 1 \\
     4 & 1 \\
     5 & 1
\end{pmatrix} 
$

2. Знайти коефіцієнти k і b за допомогою:

```
x = [k, b]
x = np.linalg.lstsq(A, y, rcond=None)[0]
```

3. Обчислити прогноз на 6-ту годину:

   `y_hat_6 = k * 6 + b`

4. Вивести рівняння тренду та прогноз.

---

## Опціонально: нормальне рівняння

Метод МНК можна записати як:

$(A^T A) x = A^T y$

Кроки:

1. Обчислити $M = A^T @ A$
2. Обчислити $v = A^T @ y$
3. Розв'язати систему:

   `x_manual = np.linalg.solve(M, v)`

4. Порівняти `x_manual` з результатом з `lstsq` — вони мають збігатися.


In [9]:
import numpy as np

# Дані
t = np.array([1, 2, 3, 4, 5], dtype=float)
y = np.array([22, 28, 37, 45, 53], dtype=float)

# 1. Формуємо матрицю A: стовпчик t і стовпчик одиниць
A = np.column_stack((t, np.ones_like(t)))

print("Matrix A:")
print(A)
print("\nVector y:")
print(y)

# 2. Розв'язання через np.linalg.lstsq
coeffs, residuals, rank, s = np.linalg.lstsq(A, y, rcond=None)
k, b = coeffs

print("\nКоефіцієнти (через lstsq):")
print("k (нахил) =", k)
print("b (зсув)  =", b)

# 3. Прогноз на 6-ту годину
t_future = 6
y_hat_6 = k * t_future + b
print(f"\nПрогнозоване навантаження на {t_future}-ту годину: y = {y_hat_6}")

print(f"\nРівняння тренду: y = {k} * t + {b}")

# 4*. Реалізація через нормальне рівняння
AT = A.T
ATA = AT @ A
ATy = AT @ y

x_manual = np.linalg.solve(ATA, ATy)
k_manual, b_manual = x_manual

print("\nКоефіцієнти (через нормальне рівняння):")
print("k_manual =", k_manual)
print("b_manual =", b_manual)

# Порівняння
print("\nПорівняння результатів:")
print("Різниця k:", k - k_manual)
print("Різниця b:", b - b_manual)


Matrix A:
[[1. 1.]
 [2. 1.]
 [3. 1.]
 [4. 1.]
 [5. 1.]]

Vector y:
[22. 28. 37. 45. 53.]

Коефіцієнти (через lstsq):
k (нахил) = 7.900000000000002
b (зсув)  = 13.299999999999985

Прогнозоване навантаження на 6-ту годину: y = 60.699999999999996

Рівняння тренду: y = 7.900000000000002 * t + 13.299999999999985

Коефіцієнти (через нормальне рівняння):
k_manual = 7.9
b_manual = 13.300000000000002

Порівняння результатів:
Різниця k: 1.7763568394002505e-15
Різниця b: -1.7763568394002505e-14
